### ISSUE TITLE
Employer

### ISSUE THREAD

**Issue by codeschris** [Swahilipot-Hub-Developers/fursa2.0-web#7]
# To-do:
- [x] Registration page
- [x] Login page
- [x] Password reset

## Dashboard
- [ ] Profile view
- [ ] Profile edit
- [x] Create job
- [ ] View seekers with matching profile
- [ ] View applications (probably by id)
- [x] Change application status

**Comment by codeschris** [comment]
# To-do:
- [ ] Registration page
- [ ] Login page
- [ ] Password reset

## Dashboard
- [ ] Profile view
- [ ] Profile edit
- [ ] Create job
- [ ] View seekers with matching profile
- [ ] View applications
- [ ] Change application status
